### ISSUE TITLE
Remove HIDECANCEL or add an exception handler

### ISSUE THREAD

**Issue by CaledoniaProject** [synacktiv/dotNIET#1]
I've accidentally ran dotNIET against a non-dotNET application. It crashes and the wait dialog is not closable (You've specified `HIDECANCEL`), please add an exception handler and close the wait dialog.

Steps to reproduce:
1. Install dotNIET: https://github.com/synacktiv/dotNIET
2. Analyze /bin/ls, anything that’s not a PE file
3. The “Please wait …” dialog popped up and the plugin crashed
4. Try to close the “Please wait” dialog and it won’t work

Related lines:

```
ida_kernwin.show_wait_box("HIDECANCEL\nIdentifying .NET "
```

![bug](https://user-images.githubusercontent.com/1357701/118735497-27001a00-b873-11eb-82ee-041fd749a1e4.jpg)

**Comment by Jissynacktiv** [comment]
Thanks for the report. I'll take a look ASAP

**Comment by Jissynacktiv** [comment]
Fixed in https://github.com/synacktiv/dotNIET/commit/8619e50686295b11882224b02d57ea6b221703cc

Thanks for the report!
